import { RaceData, ClassData, Item, Spell, BackgroundData, MonsterData, LocationData, Achievement } from './types/worldState';

export const RACES: { [key: string]: RaceData } = {
  "Human": { traits: ["Versatile", "Ambitious"], speed: 30, bonus: { all: 1 } },
  "Elf": { subraces: ["High", "Wood", "Drow", "Eladrin", "Shadar-kai", "Sea", "Astral"], traits: ["Darkvision", "Keen Senses"], speed: 30 },
  "Dwarf": { subraces: ["Hill", "Mountain", "Duergar"], traits: ["Darkvision", "Resilience"], speed: 25 },
  "Halfling": { subraces: ["Lightfoot", "Stout"], traits: ["Lucky", "Brave"], speed: 25 },
  "Gnome": { subraces: ["Forest", "Rock", "Deep"], traits: ["Cunning"], speed: 25 },
  "Dragonborn": { subraces: ["Chromatic", "Metallic", "Gem"], traits: ["Breath Weapon"], speed: 30 },
  "Tiefling": { traits: ["Darkvision", "Hellish Resistance"], speed: 30 },
  "Half-Orc": { traits: ["Relentless Endurance"], speed: 30 },
  "Half-Elf": { traits: ["Fey Ancestry"], speed: 30 },
  "Aarakocra": { traits: ["Flight"], speed: 25 }, "Aasimar": { traits: ["Healing Hands", "Light Bearer"], speed: 30 }, "Bugbear": { traits: ["Long Limbed", "Sneaky"], speed: 30 }, "Centaur": { traits: ["Charge", "Equine Build"], speed: 40 }, "Changeling": { traits: ["Shapechanger"], speed: 30 }, "Dhampir": { traits: ["Spider Climb", "Vampiric Bite"], speed: 35 }, "Fairy": { traits: ["Flight", "Fey Magic"], speed: 30 }, "Firbolg": { traits: ["Hidden Step", "Speech of Beast"], speed: 30 }, "Genasi": { subraces: ["Air", "Earth", "Fire", "Water"], traits: ["Elemental Legacy"], speed: 30 }, "Gith": { subraces: ["Githyanki", "Githzerai"], traits: ["Psionics"], speed: 30 }, "Goblin": { traits: ["Nimble Escape"], speed: 30 }, "Goliath": { traits: ["Stone's Endurance"], speed: 30 }, "Harengon": { traits: ["Rabbit Hop", "Lucky Footwork"], speed: 30 }, "Kenku": { traits: ["Mimicry"], speed: 30 }, "Kobold": { traits: ["Pack Tactics"], speed: 30 }, "Leonin": { traits: ["Daunting Roar"], speed: 35 }, "Lizardfolk": { traits: ["Natural Armor", "Bite"], speed: 30 }, "Minotaur": { traits: ["Horns", "Hammering Horns"], speed: 30 }, "Orc": { traits: ["Adrenaline Rush"], speed: 30 }, "Satyr": { traits: ["Magic Resistance", "Mirthful Leaps"], speed: 35 }, "Shifter": { traits: ["Shifting"], speed: 30 }, "Tabaxi": { traits: ["Feline Agility", "Claws"], speed: 30 }, "Tortle": { traits: ["Natural Armor", "Shell Defense"], speed: 30 }, "Triton": { traits: ["Amphibious", "Control Air/Water"], speed: 30 }, "Warforged": { traits: ["Constructed Resilience", "Integrated Protection"], speed: 30 }, "Yuan-Ti": { traits: ["Magic Resistance", "Poison Immunity"], speed: 30 }, "Autognome": { traits: ["Built for Success"], speed: 30 }, "Giff": { traits: ["Firearms Knowledge"], speed: 30 }, "Hadozee": { traits: ["Glide"], speed: 30 }, "Locathah": { traits: ["Leviathan Will"], speed: 30 }, "Owlin": { traits: ["Silent Flight"], speed: 30 }, "Plasmoid": { traits: ["Amorphous"], speed: 30 }, "Reborn": { traits: ["Deathless Nature"], speed: 30 }, "Thri-kreen": { traits: ["Chameleon Carapace"], speed: 30 }, "Verdan": { traits: ["Telepathic Insight"], speed: 30 }
};
export const CLASSES: { [key: string]: ClassData } = {
  "Fighter": { hd: 10, mana: 0, stamina: 15, gear: "Chain Mail, Iron Longsword, Wooden Shield", savingThrows: ["str", "con"], skills: ["Acrobatics", "Athletics"], features: ["Second Wind", "Fighting Style"], primaryStats: ['str', 'con'] }, 
  "Wizard": { hd: 6, mana: 15, stamina: 5, gear: "Robes, Staff, Book", savingThrows: ["int", "wis"], skills: ["Arcana", "History"], features: ["Spellcasting", "Arcane Recovery"], primaryStats: ['int', 'wis'], spells: ['firebolt', 'shield'] }, 
  "Rogue": { hd: 8, mana: 0, stamina: 12, gear: "Leather Armor, Dagger", savingThrows: ["dex", "int"], skills: ["Acrobatics", "Stealth", "Sleight of Hand"], features: ["Sneak Attack", "Thieves' Cant"], primaryStats: ['dex', 'cha'] }, 
  "Cleric": { hd: 8, mana: 12, stamina: 8, gear: "Scale Mail, Mace", savingThrows: ["wis", "cha"], skills: ["Insight", "Religion"], features: ["Spellcasting", "Divine Domain"], primaryStats: ['wis', 'cha'], spells: ['heal'] }, 
  "Barbarian": { hd: 12, mana: 0, stamina: 15, gear: "Hide Armor, Axe", savingThrows: ["str", "con"], skills: ["Athletics", "Survival"], features: ["Rage", "Unarmored Defense"], primaryStats: ['str', 'con'] }, 
  "Ranger": { hd: 10, mana: 6, stamina: 10, gear: "Leather Armor, Bow", savingThrows: ["str", "dex"], skills: ["Animal Handling", "Survival"], features: ["Favored Enemy", "Natural Explorer"], primaryStats: ['dex', 'wis'] }, 
  "Paladin": { hd: 10, mana: 6, stamina: 10, gear: "Chain Mail, Hammer", savingThrows: ["wis", "cha"], skills: ["Athletics", "Persuasion"], features: ["Divine Sense", "Lay on Hands"], primaryStats: ['str', 'cha'], spells: ['heal'] }, 
  "Monk": { hd: 8, mana: 4, stamina: 15, gear: "Robes, Staff", savingThrows: ["str", "dex"], skills: ["Acrobatics", "Insight"], features: ["Unarmored Defense", "Martial Arts"], primaryStats: ['dex', 'wis'] }, 
  "Sorcerer": { hd: 6, mana: 15, stamina: 3, gear: "Dagger, Arcane Focus", savingThrows: ["con", "cha"], skills: ["Arcana", "Deception"], features: ["Spellcasting", "Sorcerous Origin"], primaryStats: ['cha', 'con'], spells: ['firebolt'] }, 
  "Warlock": { hd: 8, mana: 10, stamina: 5, gear: "Spear, Component Pouch", savingThrows: ["wis", "cha"], skills: ["Arcana", "Intimidation"], features: ["Otherworldly Patron", "Pact Magic"], primaryStats: ['cha', 'int'], spells: ['firebolt'] }, 
  "Artificer": { hd: 8, mana: 8, stamina: 5, gear: "Thieves' Tools, Crossbow", savingThrows: ["con", "int"], skills: ["Arcana", "Investigation"], features: ["Magical Tinkering", "Infuse Item"], primaryStats: ['int', 'con'], spells: ['firebolt'] }, 
  "Bard": { hd: 8, mana: 12, stamina: 5, gear: "Lute, Leather Armor", savingThrows: ["dex", "cha"], skills: ["Performance", "Persuasion"], features: ["Bardic Inspiration", "Spellcasting"], primaryStats: ['cha', 'dex'], spells: ['heal'] }, 
  "Druid": { hd: 8, mana: 12, stamina: 5, gear: "Scimitar, Wooden Shield", savingThrows: ["int", "wis"], skills: ["Nature", "Survival"], features: ["Druidic", "Spellcasting"], primaryStats: ['wis', 'con'], spells: ['heal'] }
};
export const BACKGROUNDS: { [key: string]: BackgroundData } = {
    "Acolyte": { skills: ["Insight", "Religion"], gear: "Holy Symbol, Prayer Book", feature: "Shelter of the Faithful" },
    "Soldier": { skills: ["Athletics", "Intimidation"], gear: "Insignia of Rank, Trophy", feature: "Military Rank" },
    "Criminal": { skills: ["Deception", "Stealth"], gear: "Crowbar, Dark Clothes", feature: "Criminal Contact" },
    "Folk Hero": { skills: ["Animal Handling", "Survival"], gear: "Shovel, Iron Pot", feature: "Rustic Hospitality" },
    "Sage": { skills: ["Arcana", "History"], gear: "Bottle of Ink, Quill", feature: "Researcher" },
    "Charlatan": { skills: ["Deception", "Sleight of Hand"], gear: "Fine Clothes, Disguise Kit", feature: "False Identity" }
};
export const ITEMS_DB: Item[] = [ 
    { id: 'pot_heal', name: "Healing Potion", type: "consumable", rarity: "common", value: 500, weight: 0.5, effect: { hp: 10 } }, 
    { id: 'ration', name: "Ration (Day)", type: "food", rarity: "common", value: 50, weight: 2, effect: { hunger: -1 } }, 
    { id: 'waterskin', name: "Waterskin (Full)", type: "water", rarity: "common", value: 20, weight: 5, effect: { thirst: -0.5 } }, 
    
    // Weapons
    { id: 'sword_iron', name: "Iron Longsword", type: "weapon", rarity: "common", slot: "mainHand", power: 3, weight: 3, value: 1000 }, 
    { id: 'axe_great', name: "Great Axe", type: "weapon", rarity: "uncommon", slot: "mainHand", twoHanded: true, power: 5, weight: 7, value: 1500 }, 
    { id: 'dagger_iron', name: "Dagger", type: "weapon", rarity: "common", slot: "mainHand", power: 2, weight: 1, value: 200 },
    { id: 'mace_iron', name: "Mace", type: "weapon", rarity: "common", slot: "mainHand", power: 3, weight: 4, value: 500 },
    { id: 'axe_iron', name: "Axe", type: "weapon", rarity: "common", slot: "mainHand", power: 3, weight: 2, value: 500 },
    { id: 'bow_short', name: "Bow", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, power: 3, weight: 2, value: 2500 },
    { id: 'hammer_war', name: "Hammer", type: "weapon", rarity: "common", slot: "mainHand", power: 4, weight: 2, value: 1500 },
    { id: 'staff_wood', name: "Staff", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, power: 2, weight: 4, value: 500 },
    { id: 'spear_wood', name: "Spear", type: "weapon", rarity: "common", slot: "mainHand", power: 3, weight: 3, value: 100 },
    { id: 'crossbow_light', name: "Crossbow", type: "weapon", rarity: "common", slot: "mainHand", twoHanded: true, power: 4, weight: 5, value: 2500 },
    { id: 'scimitar', name: "Scimitar", type: "weapon", rarity: "common", slot: "mainHand", power: 3, weight: 3, value: 2500 },
    
    // Armor
    { id: 'shield_wood', name: "Wooden Shield", type: "armor", rarity: "common", slot: "offHand", ac: 2, weight: 6, value: 500 }, 
    { id: 'helmet_iron', name: "Iron Helmet", type: "armor", rarity: "common", slot: "head", ac: 2, weight: 4, value: 750 },
    { id: 'armor_leather', name: "Leather Armor", type: "armor", rarity: "common", slot: "chest", ac: 11, weight: 10, value: 1500 },
    { id: 'armor_chain', name: "Chain Mail", type: "armor", rarity: "common", slot: "chest", ac: 16, weight: 55, value: 7500 },
    { id: 'armor_plate', name: "Plate Armor", type: "armor", rarity: "rare", slot: "chest", ac: 18, weight: 65, value: 150000 },
    { id: 'greaves_iron', name: "Iron Greaves", type: "armor", rarity: "common", slot: "legs", ac: 3, weight: 10, value: 1000 },
    { id: 'gauntlets_leather', name: "Leather Gauntlets", type: "armor", rarity: "common", slot: "hands", ac: 1, weight: 1, value: 250 },
    { id: 'boots_leather', name: "Leather Boots", type: "armor", rarity: "common", slot: "feet", ac: 1, weight: 2, value: 250 },
    { id: 'robes', name: "Robes", type: "armor", rarity: "common", slot: "chest", ac: 10, weight: 4, value: 200 },
    { id: 'armor_scale', name: "Scale Mail", type: "armor", rarity: "common", slot: "chest", ac: 14, weight: 45, value: 5000 },
    { id: 'armor_hide', name: "Hide Armor", type: "armor", rarity: "common", slot: "chest", ac: 12, weight: 12, value: 1000 },

    // Accessories
    { id: 'ring_prot', name: "Ring of Protection", type: "accessory", rarity: "rare", slot: "ring", ac: 1, weight: 0.1, value: 5000 },
    { id: 'amulet_health', name: "Amulet of Health", type: "accessory", rarity: "rare", slot: "amulet", weight: 0.2, value: 7500, statsBonus: { con: 2 } },
    
    // Tools & Misc (Not equippable, so no slot)
    { id: 'book_spell', name: "Book", type: "tool", rarity: "common", weight: 3, value: 2500 },
    { id: 'focus_arcane', name: "Arcane Focus", type: "tool", rarity: "common", weight: 1, value: 1000 },
    { id: 'pouch_component', name: "Component Pouch", type: "tool", rarity: "common", weight: 2, value: 2500 },
    { id: 'tools_thieves', name: "Thieves' Tools", type: "tool", rarity: "common", weight: 1, value: 2500 },
    { id: 'lute', name: "Lute", type: "tool", rarity: "common", weight: 2, value: 3500 },

    // === MAGICAL WEAPONS ===
    { id: 'sword_flame', name: "Flametongue Sword", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 3, value: 25000, effect: { fire: 4 } },
    { id: 'sword_frost', name: "Frostbrand Sword", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 3, value: 25000, effect: { cold: 4 } },
    { id: 'sword_vorpal', name: "Vorpal Sword", type: "weapon", rarity: "legendary", slot: "mainHand", power: 10, weight: 3, value: 100000 },
    { id: 'sword_holy', name: "Holy Avenger", type: "weapon", rarity: "legendary", slot: "mainHand", power: 8, weight: 4, value: 80000, effect: { radiant: 6 } },
    { id: 'dagger_venom', name: "Dagger of Venom", type: "weapon", rarity: "rare", slot: "mainHand", power: 4, weight: 1, value: 15000, effect: { poison: 5 } },
    { id: 'dagger_assassin', name: "Assassin's Blade", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 1, value: 20000 },
    { id: 'axe_berserker', name: "Berserker Axe", type: "weapon", rarity: "rare", slot: "mainHand", power: 7, weight: 7, value: 18000, twoHanded: true },
    { id: 'hammer_thunder', name: "Hammer of Thunderbolts", type: "weapon", rarity: "legendary", slot: "mainHand", power: 9, weight: 10, value: 75000, effect: { lightning: 6 } },
    { id: 'staff_power', name: "Staff of Power", type: "weapon", rarity: "legendary", slot: "mainHand", power: 5, weight: 5, value: 100000, twoHanded: true },
    { id: 'staff_magi', name: "Staff of the Magi", type: "weapon", rarity: "legendary", slot: "mainHand", power: 6, weight: 5, value: 150000, twoHanded: true },
    { id: 'bow_oath', name: "Oathbow", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 2, value: 35000, twoHanded: true },
    { id: 'bow_lightning', name: "Bow of Lightning", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 2, value: 28000, twoHanded: true, effect: { lightning: 3 } },
    { id: 'trident_fish', name: "Trident of Fish Command", type: "weapon", rarity: "uncommon", slot: "mainHand", power: 4, weight: 4, value: 8000 },
    { id: 'mace_disruption', name: "Mace of Disruption", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 4, value: 22000, effect: { radiant: 4 } },
    { id: 'mace_smiting', name: "Mace of Smiting", type: "weapon", rarity: "rare", slot: "mainHand", power: 6, weight: 5, value: 25000 },
    { id: 'scimitar_speed', name: "Scimitar of Speed", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 3, value: 30000 },
    { id: 'sword_dancing', name: "Dancing Sword", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 3, value: 35000 },
    { id: 'sword_luck', name: "Luck Blade", type: "weapon", rarity: "legendary", slot: "mainHand", power: 6, weight: 3, value: 90000 },
    { id: 'sword_nine', name: "Nine Lives Stealer", type: "weapon", rarity: "rare", slot: "mainHand", power: 5, weight: 3, value: 40000 },
    { id: 'javelin_lightning', name: "Javelin of Lightning", type: "weapon", rarity: "uncommon", slot: "mainHand", power: 4, weight: 2, value: 8000, effect: { lightning: 4 } },

    // === MAGICAL ARMOR ===
    { id: 'armor_mithral', name: "Mithral Chain Shirt", type: "armor", rarity: "uncommon", slot: "chest", ac: 13, weight: 10, value: 15000 },
    { id: 'armor_adamantine', name: "Adamantine Plate", type: "armor", rarity: "rare", slot: "chest", ac: 18, weight: 60, value: 50000 },
    { id: 'armor_dragon_red', name: "Red Dragon Scale Mail", type: "armor", rarity: "rare", slot: "chest", ac: 14, weight: 45, value: 45000 },
    { id: 'armor_dragon_blue', name: "Blue Dragon Scale Mail", type: "armor", rarity: "rare", slot: "chest", ac: 14, weight: 45, value: 45000 },
    { id: 'armor_elven', name: "Elven Chain", type: "armor", rarity: "rare", slot: "chest", ac: 14, weight: 20, value: 35000 },
    { id: 'armor_demon', name: "Demon Armor", type: "armor", rarity: "rare", slot: "chest", ac: 17, weight: 65, value: 60000 },
    { id: 'armor_invuln', name: "Armor of Invulnerability", type: "armor", rarity: "legendary", slot: "chest", ac: 18, weight: 65, value: 150000 },
    { id: 'shield_animated', name: "Animated Shield", type: "armor", rarity: "rare", slot: "offHand", ac: 3, weight: 6, value: 35000 },
    { id: 'shield_arrow', name: "Arrow-Catching Shield", type: "armor", rarity: "rare", slot: "offHand", ac: 3, weight: 6, value: 30000 },
    { id: 'shield_spell', name: "Spellguard Shield", type: "armor", rarity: "rare", slot: "offHand", ac: 2, weight: 6, value: 40000 },
    { id: 'helm_brilliance', name: "Helm of Brilliance", type: "armor", rarity: "rare", slot: "head", ac: 1, weight: 3, value: 50000 },
    { id: 'helm_telepathy', name: "Helm of Telepathy", type: "armor", rarity: "uncommon", slot: "head", ac: 0, weight: 2, value: 12000 },
    { id: 'helm_comprehend', name: "Helm of Comprehending Languages", type: "armor", rarity: "uncommon", slot: "head", ac: 0, weight: 2, value: 5000 },
    { id: 'boots_speed', name: "Boots of Speed", type: "armor", rarity: "rare", slot: "feet", ac: 0, weight: 1, value: 35000 },
    { id: 'boots_elven', name: "Boots of Elvenkind", type: "armor", rarity: "uncommon", slot: "feet", ac: 0, weight: 1, value: 8000 },
    { id: 'boots_striding', name: "Boots of Striding and Springing", type: "armor", rarity: "uncommon", slot: "feet", ac: 0, weight: 1, value: 6000 },
    { id: 'boots_levitation', name: "Boots of Levitation", type: "armor", rarity: "rare", slot: "feet", ac: 0, weight: 1, value: 25000 },
    { id: 'boots_flying', name: "Winged Boots", type: "armor", rarity: "rare", slot: "feet", ac: 0, weight: 1, value: 45000 },
    { id: 'gloves_missile', name: "Gloves of Missile Snaring", type: "armor", rarity: "uncommon", slot: "hands", ac: 0, weight: 0.5, value: 8000 },
    { id: 'gloves_thievery', name: "Gloves of Thievery", type: "armor", rarity: "uncommon", slot: "hands", ac: 0, weight: 0.5, value: 6000 },
    { id: 'gauntlets_ogre', name: "Gauntlets of Ogre Power", type: "armor", rarity: "uncommon", slot: "hands", ac: 1, weight: 2, value: 15000, statsBonus: { str: 4 } },
    { id: 'cloak_displacement', name: "Cloak of Displacement", type: "armor", rarity: "rare", slot: "cloak", ac: 0, weight: 1, value: 40000 },
    { id: 'cloak_elven', name: "Cloak of Elvenkind", type: "armor", rarity: "uncommon", slot: "cloak", ac: 0, weight: 1, value: 8000 },
    { id: 'cloak_protection', name: "Cloak of Protection", type: "armor", rarity: "uncommon", slot: "cloak", ac: 1, weight: 1, value: 15000 },
    { id: 'cloak_bat', name: "Cloak of the Bat", type: "armor", rarity: "rare", slot: "cloak", ac: 0, weight: 1, value: 35000 },
    { id: 'cloak_manta', name: "Cloak of the Manta Ray", type: "armor", rarity: "uncommon", slot: "cloak", ac: 0, weight: 1, value: 5000 },

    // === MAGICAL ACCESSORIES ===
    { id: 'ring_resist_fire', name: "Ring of Fire Resistance", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 20000 },
    { id: 'ring_resist_cold', name: "Ring of Cold Resistance", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 20000 },
    { id: 'ring_invisibility', name: "Ring of Invisibility", type: "accessory", rarity: "legendary", slot: "ring", weight: 0.1, value: 100000 },
    { id: 'ring_spell_storing', name: "Ring of Spell Storing", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 45000 },
    { id: 'ring_regeneration', name: "Ring of Regeneration", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 55000 },
    { id: 'ring_evasion', name: "Ring of Evasion", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 30000 },
    { id: 'ring_free_action', name: "Ring of Free Action", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 25000 },
    { id: 'ring_telekinesis', name: "Ring of Telekinesis", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 50000 },
    { id: 'ring_x_ray', name: "Ring of X-Ray Vision", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 35000 },
    { id: 'ring_shooting_stars', name: "Ring of Shooting Stars", type: "accessory", rarity: "rare", slot: "ring", weight: 0.1, value: 40000 },
    { id: 'amulet_proof_loc', name: "Amulet of Proof Against Detection", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 12000 },
    { id: 'amulet_planes', name: "Amulet of the Planes", type: "accessory", rarity: "rare", slot: "amulet", weight: 0.3, value: 75000 },
    { id: 'periapt_health', name: "Periapt of Health", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 8000 },
    { id: 'periapt_wound', name: "Periapt of Wound Closure", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 12000 },
    { id: 'scarab_protection', name: "Scarab of Protection", type: "accessory", rarity: "legendary", slot: "amulet", weight: 0.3, value: 100000 },
    { id: 'brooch_shielding', name: "Brooch of Shielding", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.1, value: 10000 },
    { id: 'belt_giant_str', name: "Belt of Giant Strength", type: "accessory", rarity: "rare", slot: "belt", weight: 2, value: 50000, statsBonus: { str: 6 } },
    { id: 'belt_dwarvenkind', name: "Belt of Dwarvenkind", type: "accessory", rarity: "rare", slot: "belt", weight: 2, value: 35000, statsBonus: { con: 2 } },
    { id: 'headband_intellect', name: "Headband of Intellect", type: "accessory", rarity: "uncommon", slot: "head", weight: 0.2, value: 20000, statsBonus: { int: 4 } },
    { id: 'circlet_blasting', name: "Circlet of Blasting", type: "accessory", rarity: "uncommon", slot: "head", weight: 0.2, value: 15000 },
    { id: 'ioun_fortitude', name: "Ioun Stone of Fortitude", type: "accessory", rarity: "rare", slot: "ring", weight: 0, value: 40000, statsBonus: { con: 2 } },
    { id: 'ioun_insight', name: "Ioun Stone of Insight", type: "accessory", rarity: "rare", slot: "ring", weight: 0, value: 40000, statsBonus: { wis: 2 } },
    { id: 'ioun_intellect', name: "Ioun Stone of Intellect", type: "accessory", rarity: "rare", slot: "ring", weight: 0, value: 40000, statsBonus: { int: 2 } },

    // === POTIONS ===
    { id: 'pot_heal_greater', name: "Greater Healing Potion", type: "consumable", rarity: "uncommon", value: 1500, weight: 0.5, effect: { hp: 25 } },
    { id: 'pot_heal_superior', name: "Superior Healing Potion", type: "consumable", rarity: "rare", value: 5000, weight: 0.5, effect: { hp: 50 } },
    { id: 'pot_heal_supreme', name: "Supreme Healing Potion", type: "consumable", rarity: "rare", value: 15000, weight: 0.5, effect: { hp: 100 } },
    { id: 'pot_mana', name: "Mana Potion", type: "consumable", rarity: "uncommon", value: 1000, weight: 0.5, effect: { mana: 15 } },
    { id: 'pot_mana_greater', name: "Greater Mana Potion", type: "consumable", rarity: "rare", value: 3000, weight: 0.5, effect: { mana: 30 } },
    { id: 'pot_stamina', name: "Stamina Potion", type: "consumable", rarity: "uncommon", value: 800, weight: 0.5, effect: { stamina: 15 } },
    { id: 'pot_giant_str', name: "Potion of Giant Strength", type: "consumable", rarity: "rare", value: 8000, weight: 0.5, effect: { str_temp: 6 } },
    { id: 'pot_heroism', name: "Potion of Heroism", type: "consumable", rarity: "rare", value: 5000, weight: 0.5, effect: { temp_hp: 10 } },
    { id: 'pot_speed', name: "Potion of Speed", type: "consumable", rarity: "rare", value: 8000, weight: 0.5 },
    { id: 'pot_flying', name: "Potion of Flying", type: "consumable", rarity: "rare", value: 10000, weight: 0.5 },
    { id: 'pot_invisibility', name: "Potion of Invisibility", type: "consumable", rarity: "rare", value: 12000, weight: 0.5 },
    { id: 'pot_resistance_fire', name: "Potion of Fire Resistance", type: "consumable", rarity: "uncommon", value: 3000, weight: 0.5 },
    { id: 'pot_resistance_cold', name: "Potion of Cold Resistance", type: "consumable", rarity: "uncommon", value: 3000, weight: 0.5 },
    { id: 'pot_water_breathing', name: "Potion of Water Breathing", type: "consumable", rarity: "uncommon", value: 2000, weight: 0.5 },
    { id: 'pot_mind_reading', name: "Potion of Mind Reading", type: "consumable", rarity: "rare", value: 6000, weight: 0.5 },
    { id: 'antitoxin', name: "Antitoxin", type: "consumable", rarity: "common", value: 500, weight: 0.5, effect: { poison_cure: 1 } },
    { id: 'oil_slipperiness', name: "Oil of Slipperiness", type: "consumable", rarity: "uncommon", value: 2500, weight: 0.5 },
    { id: 'oil_sharpness', name: "Oil of Sharpness", type: "consumable", rarity: "rare", value: 8000, weight: 0.5 },

    // === WONDROUS ITEMS ===
    { id: 'bag_holding', name: "Bag of Holding", type: "tool", rarity: "uncommon", weight: 0.5, value: 10000 },
    { id: 'bag_tricks', name: "Bag of Tricks", type: "tool", rarity: "uncommon", weight: 0.5, value: 8000 },
    { id: 'portable_hole', name: "Portable Hole", type: "tool", rarity: "rare", weight: 0, value: 40000 },
    { id: 'rope_climbing', name: "Rope of Climbing", type: "tool", rarity: "uncommon", weight: 3, value: 5000 },
    { id: 'rope_entanglement', name: "Rope of Entanglement", type: "tool", rarity: "rare", weight: 3, value: 20000 },
    { id: 'immovable_rod', name: "Immovable Rod", type: "tool", rarity: "uncommon", weight: 2, value: 8000 },
    { id: 'decanter_water', name: "Decanter of Endless Water", type: "tool", rarity: "uncommon", weight: 2, value: 6000 },
    { id: 'lantern_revealing', name: "Lantern of Revealing", type: "tool", rarity: "uncommon", weight: 2, value: 8000 },
    { id: 'eyes_eagle', name: "Eyes of the Eagle", type: "tool", rarity: "uncommon", weight: 0.1, value: 5000 },
    { id: 'eyes_charming', name: "Eyes of Charming", type: "tool", rarity: "uncommon", weight: 0.1, value: 10000 },
    { id: 'goggles_night', name: "Goggles of Night", type: "tool", rarity: "uncommon", weight: 0.2, value: 5000 },
    { id: 'gem_seeing', name: "Gem of Seeing", type: "tool", rarity: "rare", weight: 0.1, value: 35000 },
    { id: 'gem_brightness', name: "Gem of Brightness", type: "tool", rarity: "uncommon", weight: 0.1, value: 6000 },
    { id: 'crystal_ball', name: "Crystal Ball", type: "tool", rarity: "rare", weight: 3, value: 50000 },
    { id: 'mirror_lifetrapping', name: "Mirror of Life Trapping", type: "tool", rarity: "rare", weight: 50, value: 60000 },
    { id: 'horn_blasting', name: "Horn of Blasting", type: "tool", rarity: "rare", weight: 2, value: 25000 },
    { id: 'horn_valhalla', name: "Horn of Valhalla", type: "tool", rarity: "rare", weight: 2, value: 35000 },
    { id: 'cube_force', name: "Cube of Force", type: "tool", rarity: "rare", weight: 0.5, value: 40000 },
    { id: 'bead_force', name: "Bead of Force", type: "consumable", rarity: "rare", value: 5000, weight: 0.1 },
    { id: 'carpet_flying', name: "Carpet of Flying", type: "tool", rarity: "rare", weight: 15, value: 60000 },
    { id: 'figurine_golem', name: "Figurine of Wondrous Power (Bronze Griffon)", type: "tool", rarity: "rare", weight: 0.5, value: 35000 },
    { id: 'figurine_raven', name: "Figurine of Wondrous Power (Silver Raven)", type: "tool", rarity: "uncommon", weight: 0.3, value: 8000 },
    { id: 'necklace_fireballs', name: "Necklace of Fireballs", type: "tool", rarity: "rare", weight: 0.3, value: 30000 },
    { id: 'necklace_adaptation', name: "Necklace of Adaptation", type: "accessory", rarity: "uncommon", slot: "amulet", weight: 0.2, value: 12000 },
    { id: 'pearl_power', name: "Pearl of Power", type: "consumable", rarity: "uncommon", value: 8000, weight: 0.1 },
    { id: 'sending_stones', name: "Sending Stones", type: "tool", rarity: "uncommon", weight: 0.5, value: 10000 },
    { id: 'spell_scroll_1', name: "Spell Scroll (Level 1)", type: "consumable", rarity: "common", value: 500, weight: 0.1 },
    { id: 'spell_scroll_3', name: "Spell Scroll (Level 3)", type: "consumable", rarity: "uncommon", value: 2000, weight: 0.1 },
    { id: 'spell_scroll_5', name: "Spell Scroll (Level 5)", type: "consumable", rarity: "rare", value: 8000, weight: 0.1 },

    // === LEGENDARY ARTIFACTS ===
    { id: 'book_vile', name: "Book of Vile Darkness", type: "tool", rarity: "legendary", weight: 5, value: 250000 },
    { id: 'book_exalted', name: "Book of Exalted Deeds", type: "tool", rarity: "legendary", weight: 5, value: 250000 },
    { id: 'eye_vecna', name: "Eye of Vecna", type: "accessory", rarity: "legendary", slot: "head", weight: 0, value: 500000 },
    { id: 'hand_vecna', name: "Hand of Vecna", type: "accessory", rarity: "legendary", slot: "hands", weight: 1, value: 500000 },
    { id: 'orb_dragon', name: "Orb of Dragonkind", type: "tool", rarity: "legendary", weight: 3, value: 300000 },
    { id: 'talisman_sphere', name: "Talisman of the Sphere", type: "accessory", rarity: "legendary", slot: "amulet", weight: 1, value: 400000 },
    { id: 'deck_many', name: "Deck of Many Things", type: "tool", rarity: "legendary", weight: 0.5, value: 1000000 },
    { id: 'sphere_annihilation', name: "Sphere of Annihilation", type: "tool", rarity: "legendary", weight: 0, value: 750000 },
    { id: 'wand_wonder', name: "Wand of Wonder", type: "tool", rarity: "rare", weight: 1, value: 45000 },
    { id: 'wand_fireballs', name: "Wand of Fireballs", type: "tool", rarity: "rare", weight: 1, value: 50000 },
    { id: 'wand_lightning', name: "Wand of Lightning Bolts", type: "tool", rarity: "rare", weight: 1, value: 50000 },
    { id: 'wand_magic_missile', name: "Wand of Magic Missiles", type: "tool", rarity: "uncommon", weight: 1, value: 15000 },
    { id: 'wand_web', name: "Wand of Web", type: "tool", rarity: "uncommon", weight: 1, value: 12000 },
    { id: 'wand_fear', name: "Wand of Fear", type: "tool", rarity: "rare", weight: 1, value: 35000 },
    { id: 'wand_paralysis', name: "Wand of Paralysis", type: "tool", rarity: "rare", weight: 1, value: 40000 },
    { id: 'rod_absorption', name: "Rod of Absorption", type: "tool", rarity: "rare", weight: 2, value: 60000 },
    { id: 'rod_lordly', name: "Rod of Lordly Might", type: "weapon", rarity: "legendary", slot: "mainHand", power: 8, weight: 5, value: 100000 },
    { id: 'rod_security', name: "Rod of Security", type: "tool", rarity: "rare", weight: 2, value: 45000 },
];
export const SPELLS_DB: Spell[] = [
    // === CANTRIPS (Cost: 1-2) ===
    // Evocation
    { id: 'firebolt', name: "Fire Bolt", cost: 2, damage: 8, school: "Evocation", target: "enemy" },
    { id: 'ray_frost', name: "Ray of Frost", cost: 2, damage: 6, school: "Evocation", target: "enemy" },
    { id: 'shocking_grasp', name: "Shocking Grasp", cost: 2, damage: 7, school: "Evocation", target: "enemy" },
    { id: 'eldritch_blast', name: "Eldritch Blast", cost: 2, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'sacred_flame', name: "Sacred Flame", cost: 2, damage: 6, school: "Evocation", target: "enemy" },
    { id: 'toll_the_dead', name: "Toll the Dead", cost: 2, damage: 8, school: "Necromancy", target: "enemy" },
    { id: 'chill_touch', name: "Chill Touch", cost: 2, damage: 6, school: "Necromancy", target: "enemy" },
    { id: 'acid_splash', name: "Acid Splash", cost: 2, damage: 5, school: "Conjuration", target: "enemy" },
    { id: 'poison_spray', name: "Poison Spray", cost: 2, damage: 10, school: "Conjuration", target: "enemy" },
    { id: 'produce_flame', name: "Produce Flame", cost: 1, damage: 6, school: "Conjuration", target: "enemy" },
    // Utility Cantrips
    { id: 'light', name: "Light", cost: 1, buff: "Illuminated", duration: 10, school: "Evocation", target: "self" },
    { id: 'mage_hand', name: "Mage Hand", cost: 1, buff: "Spectral Hand", duration: 5, school: "Conjuration", target: "self" },
    { id: 'prestidigitation', name: "Prestidigitation", cost: 1, buff: "Minor Magic", duration: 3, school: "Transmutation", target: "self" },
    { id: 'minor_illusion', name: "Minor Illusion", cost: 1, buff: "Illusory Distraction", duration: 3, school: "Illusion", target: "self" },
    { id: 'guidance', name: "Guidance", cost: 1, buff: "Guided", duration: 1, school: "Divination", target: "ally" },
    { id: 'resistance', name: "Resistance", cost: 1, buff: "Resistant", duration: 1, school: "Abjuration", target: "ally" },
    { id: 'thaumaturgy', name: "Thaumaturgy", cost: 1, buff: "Intimidating Presence", duration: 2, school: "Transmutation", target: "self" },
    { id: 'druidcraft', name: "Druidcraft", cost: 1, buff: "Nature's Touch", duration: 3, school: "Transmutation", target: "self" },
    { id: 'spare_dying', name: "Spare the Dying", cost: 1, heal: 1, school: "Necromancy", target: "ally" },
    { id: 'blade_ward', name: "Blade Ward", cost: 1, buff: "Warded", duration: 1, school: "Abjuration", target: "self" },

    // === LEVEL 1 SPELLS (Cost: 3-5) ===
    // Healing
    { id: 'heal', name: "Cure Wounds", cost: 5, heal: 12, school: "Evocation", target: "ally" },
    { id: 'healing_word', name: "Healing Word", cost: 3, heal: 8, school: "Evocation", target: "ally" },
    { id: 'goodberry', name: "Goodberry", cost: 3, heal: 10, school: "Transmutation", target: "ally" },
    // Defense
    { id: 'shield', name: "Shield", cost: 3, buff: "Shielded", duration: 2, school: "Abjuration", target: "self" },
    { id: 'mage_armor', name: "Mage Armor", cost: 4, buff: "Mage Armor", duration: 8, school: "Abjuration", target: "self" },
    { id: 'sanctuary', name: "Sanctuary", cost: 3, buff: "Sanctuary", duration: 3, school: "Abjuration", target: "ally" },
    { id: 'shield_faith', name: "Shield of Faith", cost: 3, buff: "Faith Shield", duration: 5, school: "Abjuration", target: "ally" },
    { id: 'absorb_elements', name: "Absorb Elements", cost: 3, buff: "Elemental Absorption", duration: 1, school: "Abjuration", target: "self" },
    // Offense
    { id: 'magic_missile', name: "Magic Missile", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'burning_hands', name: "Burning Hands", cost: 4, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'thunderwave', name: "Thunderwave", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'chromatic_orb', name: "Chromatic Orb", cost: 5, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'ice_knife', name: "Ice Knife", cost: 4, damage: 12, school: "Conjuration", target: "enemy" },
    { id: 'inflict_wounds', name: "Inflict Wounds", cost: 5, damage: 16, school: "Necromancy", target: "enemy" },
    { id: 'guiding_bolt', name: "Guiding Bolt", cost: 4, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'hellish_rebuke', name: "Hellish Rebuke", cost: 4, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'witchbolt', name: "Witch Bolt", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    { id: 'earth_tremor', name: "Earth Tremor", cost: 4, damage: 10, school: "Evocation", target: "enemy" },
    // Control/Utility
    { id: 'sleep', name: "Sleep", cost: 4, buff: "Sleep Aura", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'charm_person', name: "Charm Person", cost: 4, buff: "Charmed", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'command', name: "Command", cost: 3, buff: "Commanded", duration: 1, school: "Enchantment", target: "enemy" },
    { id: 'bane', name: "Bane", cost: 4, buff: "Baned", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'bless', name: "Bless", cost: 4, buff: "Blessed", duration: 5, school: "Enchantment", target: "ally" },
    { id: 'heroism', name: "Heroism", cost: 4, buff: "Heroic", duration: 5, school: "Enchantment", target: "ally" },
    { id: 'faerie_fire', name: "Faerie Fire", cost: 4, buff: "Revealed", duration: 3, school: "Evocation", target: "enemy" },
    { id: 'entangle', name: "Entangle", cost: 4, buff: "Entangled", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'fog_cloud', name: "Fog Cloud", cost: 3, buff: "Obscured", duration: 5, school: "Conjuration", target: "self" },
    { id: 'grease', name: "Grease", cost: 3, buff: "Slippery Ground", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'disguise_self', name: "Disguise Self", cost: 3, buff: "Disguised", duration: 10, school: "Illusion", target: "self" },
    { id: 'silent_image', name: "Silent Image", cost: 3, buff: "Illusory Cover", duration: 5, school: "Illusion", target: "self" },
    { id: 'detect_magic', name: "Detect Magic", cost: 3, buff: "Magic Sight", duration: 5, school: "Divination", target: "self" },
    { id: 'identify', name: "Identify", cost: 3, buff: "Identified", duration: 1, school: "Divination", target: "self" },
    { id: 'hunters_mark', name: "Hunter's Mark", cost: 3, buff: "Marked Prey", duration: 10, school: "Divination", target: "enemy" },
    { id: 'hex', name: "Hex", cost: 3, damage: 4, school: "Enchantment", target: "enemy" },
    { id: 'false_life', name: "False Life", cost: 3, heal: 8, school: "Necromancy", target: "self" },
    { id: 'expeditious_retreat', name: "Expeditious Retreat", cost: 3, buff: "Hastened", duration: 5, school: "Transmutation", target: "self" },
    { id: 'jump', name: "Jump", cost: 3, buff: "Enhanced Leap", duration: 3, school: "Transmutation", target: "self" },
    { id: 'longstrider', name: "Longstrider", cost: 3, buff: "Swift", duration: 10, school: "Transmutation", target: "self" },
    { id: 'feather_fall', name: "Feather Fall", cost: 3, buff: "Featherweight", duration: 1, school: "Transmutation", target: "ally" },

    // === LEVEL 2 SPELLS (Cost: 6-8) ===
    // Healing
    { id: 'prayer_healing', name: "Prayer of Healing", cost: 8, heal: 18, school: "Evocation", target: "ally" },
    { id: 'lesser_restoration', name: "Lesser Restoration", cost: 6, heal: 5, school: "Abjuration", target: "ally" },
    { id: 'aid', name: "Aid", cost: 6, heal: 10, school: "Abjuration", target: "ally" },
    // Offense
    { id: 'scorching_ray', name: "Scorching Ray", cost: 7, damage: 18, school: "Evocation", target: "enemy" },
    { id: 'shatter', name: "Shatter", cost: 7, damage: 16, school: "Evocation", target: "enemy" },
    { id: 'melfs_acid_arrow', name: "Melf's Acid Arrow", cost: 7, damage: 16, school: "Evocation", target: "enemy" },
    { id: 'spiritual_weapon', name: "Spiritual Weapon", cost: 6, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'moonbeam', name: "Moonbeam", cost: 7, damage: 14, school: "Evocation", target: "enemy" },
    { id: 'flame_blade', name: "Flame Blade", cost: 6, damage: 12, school: "Evocation", target: "enemy" },
    { id: 'cloud_daggers', name: "Cloud of Daggers", cost: 6, damage: 14, school: "Conjuration", target: "enemy" },
    { id: 'ray_enfeeblement', name: "Ray of Enfeeblement", cost: 6, damage: 8, school: "Necromancy", target: "enemy" },
    { id: 'blindness', name: "Blindness/Deafness", cost: 6, buff: "Blinded", duration: 3, school: "Necromancy", target: "enemy" },
    // Defense/Utility
    { id: 'mirror_image', name: "Mirror Image", cost: 6, buff: "Mirror Images", duration: 5, school: "Illusion", target: "self" },
    { id: 'invisibility', name: "Invisibility", cost: 7, buff: "Invisible", duration: 5, school: "Illusion", target: "ally" },
    { id: 'blur', name: "Blur", cost: 6, buff: "Blurred", duration: 5, school: "Illusion", target: "self" },
    { id: 'misty_step', name: "Misty Step", cost: 6, buff: "Teleported", duration: 1, school: "Conjuration", target: "self" },
    { id: 'hold_person', name: "Hold Person", cost: 7, buff: "Paralyzed", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'crown_madness', name: "Crown of Madness", cost: 6, buff: "Maddened", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'suggestion', name: "Suggestion", cost: 7, buff: "Suggested", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'calm_emotions', name: "Calm Emotions", cost: 6, buff: "Calmed", duration: 3, school: "Enchantment", target: "ally" },
    { id: 'web', name: "Web", cost: 6, buff: "Webbed", duration: 5, school: "Conjuration", target: "enemy" },
    { id: 'spike_growth', name: "Spike Growth", cost: 7, damage: 10, school: "Transmutation", target: "enemy" },
    { id: 'barkskin', name: "Barkskin", cost: 6, buff: "Barkskin", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'enlarge_reduce', name: "Enlarge/Reduce", cost: 6, buff: "Enlarged", duration: 5, school: "Transmutation", target: "ally" },
    { id: 'heat_metal', name: "Heat Metal", cost: 7, damage: 12, school: "Transmutation", target: "enemy" },
    { id: 'see_invisibility', name: "See Invisibility", cost: 6, buff: "True Sight", duration: 10, school: "Divination", target: "self" },
    { id: 'detect_thoughts', name: "Detect Thoughts", cost: 6, buff: "Mind Reading", duration: 5, school: "Divination", target: "self" },
    { id: 'darkness', name: "Darkness", cost: 6, buff: "Magical Darkness", duration: 5, school: "Evocation", target: "self" },
    { id: 'warding_bond', name: "Warding Bond", cost: 7, buff: "Bonded Protection", duration: 10, school: "Abjuration", target: "ally" },

    // === LEVEL 3 SPELLS (Cost: 9-12) ===
    // Offense
    { id: 'fireball', name: "Fireball", cost: 10, damage: 28, school: "Evocation", target: "enemy" },
    { id: 'lightning_bolt', name: "Lightning Bolt", cost: 10, damage: 28, school: "Evocation", target: "enemy" },
    { id: 'call_lightning', name: "Call Lightning", cost: 10, damage: 24, school: "Conjuration", target: "enemy" },
    { id: 'spirit_guardians', name: "Spirit Guardians", cost: 10, damage: 20, school: "Conjuration", target: "enemy" },
    { id: 'vampiric_touch', name: "Vampiric Touch", cost: 10, damage: 18, school: "Necromancy", target: "enemy" },
    { id: 'hunger_hadar', name: "Hunger of Hadar", cost: 10, damage: 16, school: "Conjuration", target: "enemy" },
    { id: 'erupting_earth', name: "Erupting Earth", cost: 9, damage: 20, school: "Transmutation", target: "enemy" },
    { id: 'tidal_wave', name: "Tidal Wave", cost: 9, damage: 18, school: "Conjuration", target: "enemy" },
    // Healing/Support
    { id: 'mass_healing_word', name: "Mass Healing Word", cost: 10, heal: 15, school: "Evocation", target: "ally" },
    { id: 'revivify', name: "Revivify", cost: 12, heal: 30, school: "Necromancy", target: "ally" },
    { id: 'beacon_hope', name: "Beacon of Hope", cost: 9, buff: "Hopeful", duration: 5, school: "Abjuration", target: "ally" },
    // Control/Utility
    { id: 'counterspell', name: "Counterspell", cost: 9, buff: "Spell Negated", duration: 1, school: "Abjuration", target: "enemy" },
    { id: 'dispel_magic', name: "Dispel Magic", cost: 9, buff: "Dispelled", duration: 1, school: "Abjuration", target: "enemy" },
    { id: 'remove_curse', name: "Remove Curse", cost: 9, heal: 5, school: "Abjuration", target: "ally" },
    { id: 'haste', name: "Haste", cost: 10, buff: "Hasted", duration: 5, school: "Transmutation", target: "ally" },
    { id: 'slow', name: "Slow", cost: 10, buff: "Slowed", duration: 5, school: "Transmutation", target: "enemy" },
    { id: 'fly', name: "Fly", cost: 10, buff: "Flying", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'fear', name: "Fear", cost: 10, buff: "Frightened", duration: 3, school: "Illusion", target: "enemy" },
    { id: 'hypnotic_pattern', name: "Hypnotic Pattern", cost: 10, buff: "Hypnotized", duration: 3, school: "Illusion", target: "enemy" },
    { id: 'major_image', name: "Major Image", cost: 9, buff: "Grand Illusion", duration: 5, school: "Illusion", target: "self" },
    { id: 'bestow_curse', name: "Bestow Curse", cost: 10, buff: "Cursed", duration: 5, school: "Necromancy", target: "enemy" },
    { id: 'animate_dead', name: "Animate Dead", cost: 10, buff: "Undead Minion", duration: 24, school: "Necromancy", target: "self" },
    { id: 'stinking_cloud', name: "Stinking Cloud", cost: 9, buff: "Nauseated", duration: 3, school: "Conjuration", target: "enemy" },
    { id: 'sleet_storm', name: "Sleet Storm", cost: 9, damage: 10, school: "Conjuration", target: "enemy" },
    { id: 'plant_growth', name: "Plant Growth", cost: 9, buff: "Overgrown Terrain", duration: 10, school: "Transmutation", target: "self" },
    { id: 'protection_energy', name: "Protection from Energy", cost: 9, buff: "Energy Resistance", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'clairvoyance', name: "Clairvoyance", cost: 10, buff: "Remote Viewing", duration: 5, school: "Divination", target: "self" },
    { id: 'tongues', name: "Tongues", cost: 9, buff: "Universal Speech", duration: 10, school: "Divination", target: "ally" },

    // === LEVEL 4 SPELLS (Cost: 13-16) ===
    // Offense
    { id: 'ice_storm', name: "Ice Storm", cost: 14, damage: 32, school: "Evocation", target: "enemy" },
    { id: 'blight', name: "Blight", cost: 14, damage: 36, school: "Necromancy", target: "enemy" },
    { id: 'phantasmal_killer', name: "Phantasmal Killer", cost: 14, damage: 28, school: "Illusion", target: "enemy" },
    { id: 'fire_shield', name: "Fire Shield", cost: 13, damage: 10, school: "Evocation", target: "self" },
    { id: 'vitriolic_sphere', name: "Vitriolic Sphere", cost: 14, damage: 34, school: "Evocation", target: "enemy" },
    // Utility/Control
    { id: 'greater_invisibility', name: "Greater Invisibility", cost: 14, buff: "Greater Invisibility", duration: 5, school: "Illusion", target: "ally" },
    { id: 'polymorph', name: "Polymorph", cost: 15, buff: "Polymorphed", duration: 10, school: "Transmutation", target: "ally" },
    { id: 'banishment', name: "Banishment", cost: 15, buff: "Banished", duration: 5, school: "Abjuration", target: "enemy" },
    { id: 'dimension_door', name: "Dimension Door", cost: 14, buff: "Dimensional Travel", duration: 1, school: "Conjuration", target: "self" },
    { id: 'confusion', name: "Confusion", cost: 14, buff: "Confused", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'compulsion', name: "Compulsion", cost: 14, buff: "Compelled", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'dominate_beast', name: "Dominate Beast", cost: 14, buff: "Beast Dominated", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'freedom_movement', name: "Freedom of Movement", cost: 13, buff: "Unrestricted", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'stoneskin', name: "Stoneskin", cost: 15, buff: "Stone Skin", duration: 10, school: "Abjuration", target: "ally" },
    { id: 'death_ward', name: "Death Ward", cost: 14, buff: "Death Warded", duration: 24, school: "Abjuration", target: "ally" },
    { id: 'locate_creature', name: "Locate Creature", cost: 13, buff: "Creature Tracking", duration: 10, school: "Divination", target: "self" },
    { id: 'arcane_eye', name: "Arcane Eye", cost: 13, buff: "Arcane Vision", duration: 10, school: "Divination", target: "self" },

    // === LEVEL 5 SPELLS (Cost: 17-20) ===
    // Offense
    { id: 'cone_cold', name: "Cone of Cold", cost: 18, damage: 42, school: "Evocation", target: "enemy" },
    { id: 'flame_strike', name: "Flame Strike", cost: 18, damage: 38, school: "Evocation", target: "enemy" },
    { id: 'cloudkill', name: "Cloudkill", cost: 18, damage: 30, school: "Conjuration", target: "enemy" },
    { id: 'insect_plague', name: "Insect Plague", cost: 17, damage: 28, school: "Conjuration", target: "enemy" },
    { id: 'destructive_wave', name: "Destructive Wave", cost: 18, damage: 40, school: "Evocation", target: "enemy" },
    { id: 'synaptic_static', name: "Synaptic Static", cost: 18, damage: 36, school: "Enchantment", target: "enemy" },
    // Healing/Support
    { id: 'mass_cure_wounds', name: "Mass Cure Wounds", cost: 18, heal: 25, school: "Evocation", target: "ally" },
    { id: 'greater_restoration', name: "Greater Restoration", cost: 18, heal: 20, school: "Abjuration", target: "ally" },
    { id: 'raise_dead', name: "Raise Dead", cost: 20, heal: 50, school: "Necromancy", target: "ally" },
    // Control/Utility
    { id: 'hold_monster', name: "Hold Monster", cost: 18, buff: "Monster Paralyzed", duration: 3, school: "Enchantment", target: "enemy" },
    { id: 'dominate_person', name: "Dominate Person", cost: 18, buff: "Person Dominated", duration: 5, school: "Enchantment", target: "enemy" },
    { id: 'telekinesis', name: "Telekinesis", cost: 17, buff: "Telekinetic Control", duration: 5, school: "Transmutation", target: "self" },
    { id: 'animate_objects', name: "Animate Objects", cost: 18, buff: "Animated Servants", duration: 5, school: "Transmutation", target: "self" },
    { id: 'wall_force', name: "Wall of Force", cost: 18, buff: "Force Barrier", duration: 5, school: "Evocation", target: "self" },
    { id: 'wall_stone', name: "Wall of Stone", cost: 17, buff: "Stone Barrier", duration: 10, school: "Evocation", target: "self" },
    { id: 'conjure_elemental', name: "Conjure Elemental", cost: 18, buff: "Elemental Ally", duration: 10, school: "Conjuration", target: "self" },
    { id: 'teleportation_circle', name: "Teleportation Circle", cost: 17, buff: "Portal Open", duration: 1, school: "Conjuration", target: "self" },
    { id: 'scrying', name: "Scrying", cost: 17, buff: "Scrying Vision", duration: 5, school: "Divination", target: "self" },
    { id: 'legend_lore', name: "Legend Lore", cost: 17, buff: "Ancient Knowledge", duration: 1, school: "Divination", target: "self" },
    { id: 'dream', name: "Dream", cost: 17, buff: "Dream Message", duration: 8, school: "Illusion", target: "ally" },
    { id: 'mislead', name: "Mislead", cost: 17, buff: "Illusory Double", duration: 5, school: "Illusion", target: "self" },
    { id: 'modify_memory', name: "Modify Memory", cost: 18, buff: "Memory Altered", duration: 1, school: "Enchantment", target: "enemy" },
    { id: 'geas', name: "Geas", cost: 18, buff: "Geased", duration: 720, school: "Enchantment", target: "enemy" },
    { id: 'antilife_shell', name: "Antilife Shell", cost: 17, buff: "Life Barrier", duration: 10, school: "Abjuration", target: "self" },
    { id: 'dispel_evil', name: "Dispel Evil and Good", cost: 17, buff: "Planar Protection", duration: 5, school: "Abjuration", target: "self" },
];
export const FEATS_DB = [ { id: 'alert', name: "Alert", desc: "+5 Initiative, cannot be surprised.", req: "None" }, { id: 'tough', name: "Tough", desc: "+2 HP per level.", req: "None" } ];

// === MONSTER BESTIARY ===
export const MONSTERS_DB: MonsterData[] = [
    // === CR 0 - 1/4 (Weak Enemies) ===
    { id: 'rat', name: "Giant Rat", type: "beast", challenge: 0.125, hp: 7, ac: 12, damage: "1d4", speed: 30, xp: 25, loot: ['ration'], description: "A dog-sized rat with mange-ridden fur and gleaming red eyes." },
    { id: 'bat_swarm', name: "Swarm of Bats", type: "beast", challenge: 0.25, hp: 22, ac: 12, damage: "2d4", speed: 30, xp: 50, resistances: ["bludgeoning", "piercing", "slashing"], description: "A writhing cloud of screeching bats." },
    { id: 'goblin', name: "Goblin", type: "humanoid", challenge: 0.25, hp: 7, ac: 15, damage: "1d6+2", speed: 30, xp: 50, abilities: ["Nimble Escape"], loot: ['dagger_iron', 'ration'], description: "A small, green-skinned creature with sharp teeth and cunning eyes." },
    { id: 'kobold', name: "Kobold", type: "humanoid", challenge: 0.125, hp: 5, ac: 12, damage: "1d4+2", speed: 30, xp: 25, abilities: ["Pack Tactics", "Sunlight Sensitivity"], loot: ['dagger_iron'], description: "A small reptilian humanoid with a yipping voice." },
    { id: 'skeleton', name: "Skeleton", type: "undead", challenge: 0.25, hp: 13, ac: 13, damage: "1d6+2", speed: 30, xp: 50, immunities: ["poison"], vulnerabilities: ["bludgeoning"], loot: ['sword_iron'], description: "Animated bones held together by dark magic." },
    { id: 'zombie', name: "Zombie", type: "undead", challenge: 0.25, hp: 22, ac: 8, damage: "1d6+1", speed: 20, xp: 50, immunities: ["poison"], abilities: ["Undead Fortitude"], description: "A shambling corpse with rotting flesh and empty eyes." },
    { id: 'wolf', name: "Wolf", type: "beast", challenge: 0.25, hp: 11, ac: 13, damage: "2d4+2", speed: 40, xp: 50, abilities: ["Pack Tactics"], description: "A gray wolf with keen senses and sharp fangs." },
    { id: 'giant_spider', name: "Giant Spider", type: "beast", challenge: 0.25, hp: 26, ac: 14, damage: "1d8+3", speed: 30, xp: 50, abilities: ["Web Walker", "Web Sense"], description: "A massive spider the size of a horse." },

    // === CR 1/2 - 1 (Common Enemies) ===
    { id: 'orc', name: "Orc", type: "humanoid", challenge: 0.5, hp: 15, ac: 13, damage: "1d12+3", speed: 30, xp: 100, abilities: ["Aggressive"], loot: ['axe_iron', 'ration'], description: "A hulking gray-skinned warrior with tusks and tribal scars." },
    { id: 'hobgoblin', name: "Hobgoblin", type: "humanoid", challenge: 0.5, hp: 11, ac: 18, damage: "1d8+1", speed: 30, xp: 100, abilities: ["Martial Advantage"], loot: ['sword_iron', 'armor_chain'], description: "A disciplined goblinoid soldier in well-maintained armor." },
    { id: 'gnoll', name: "Gnoll", type: "humanoid", challenge: 0.5, hp: 22, ac: 15, damage: "1d8+2", speed: 30, xp: 100, abilities: ["Rampage"], loot: ['spear_wood'], description: "A hyena-headed savage driven by endless hunger." },
    { id: 'shadow', name: "Shadow", type: "undead", challenge: 0.5, hp: 16, ac: 12, damage: "2d6+2", speed: 40, xp: 100, immunities: ["necrotic", "poison"], resistances: ["acid", "cold", "fire", "lightning", "thunder"], abilities: ["Strength Drain", "Shadow Stealth"], description: "A dark, incorporeal shape that drains the life from the living." },
    { id: 'bugbear', name: "Bugbear", type: "humanoid", challenge: 1, hp: 27, ac: 16, damage: "2d8+2", speed: 30, xp: 200, abilities: ["Surprise Attack", "Brute"], loot: ['axe_great', 'pot_heal'], description: "A massive, hairy goblinoid that strikes from ambush." },
    { id: 'dire_wolf', name: "Dire Wolf", type: "beast", challenge: 1, hp: 37, ac: 14, damage: "2d6+3", speed: 50, xp: 200, abilities: ["Pack Tactics", "Keen Hearing and Smell"], description: "An enormous wolf, large enough to serve as a mount." },
    { id: 'ghoul', name: "Ghoul", type: "undead", challenge: 1, hp: 22, ac: 12, damage: "2d6+2", speed: 30, xp: 200, immunities: ["poison", "charmed", "exhaustion"], abilities: ["Paralyzing Touch"], description: "An undead creature that feeds on the flesh of corpses." },
    { id: 'specter', name: "Specter", type: "undead", challenge: 1, hp: 22, ac: 12, damage: "3d6", speed: 50, xp: 200, immunities: ["necrotic", "poison"], resistances: ["acid", "cold", "fire", "lightning", "thunder"], abilities: ["Life Drain", "Incorporeal Movement"], description: "A hateful spirit bound to the material world by rage." },
    { id: 'harpy', name: "Harpy", type: "monstrosity", challenge: 1, hp: 38, ac: 11, damage: "2d4+1", speed: 40, xp: 200, abilities: ["Luring Song"], description: "A winged creature with a woman's face and a vulture's body." },

    // === CR 2-3 (Challenging Enemies) ===
    { id: 'ogre', name: "Ogre", type: "giant", challenge: 2, hp: 59, ac: 11, damage: "2d8+4", speed: 40, xp: 450, loot: ['axe_great', 'pot_heal', 'ration'], description: "A dim-witted brute standing ten feet tall with yellowed tusks." },
    { id: 'gargoyle', name: "Gargoyle", type: "elemental", challenge: 2, hp: 52, ac: 15, damage: "2d6+2", speed: 60, xp: 450, immunities: ["poison"], resistances: ["bludgeoning", "piercing", "slashing"], abilities: ["False Appearance"], description: "A stone creature that lurks on castle walls, frozen until prey arrives." },
    { id: 'ghast', name: "Ghast", type: "undead", challenge: 2, hp: 36, ac: 13, damage: "2d8+3", speed: 30, xp: 450, immunities: ["poison"], abilities: ["Stench", "Paralyzing Touch"], description: "A more powerful ghoul that exudes a nauseating stench." },
    { id: 'mimic', name: "Mimic", type: "monstrosity", challenge: 2, hp: 58, ac: 12, damage: "1d8+3", speed: 15, xp: 450, abilities: ["Shapechanger", "Adhesive", "Grappler"], loot: ['ring_prot', 'pot_heal'], description: "A shapeshifting predator that disguises itself as treasure chests." },
    { id: 'werewolf', name: "Werewolf", type: "humanoid", challenge: 3, hp: 58, ac: 12, damage: "2d4+3", speed: 40, xp: 700, immunities: ["bludgeoning", "piercing", "slashing from nonmagical attacks"], abilities: ["Shapechanger", "Keen Hearing and Smell"], description: "A cursed human that transforms into a savage wolf-like beast." },
    { id: 'owlbear', name: "Owlbear", type: "monstrosity", challenge: 3, hp: 59, ac: 13, damage: "2d8+4", speed: 40, xp: 700, abilities: ["Keen Sight and Smell"], description: "A fearsome hybrid with an owl's head and a bear's body." },
    { id: 'manticore', name: "Manticore", type: "monstrosity", challenge: 3, hp: 68, ac: 14, damage: "2d6+3", speed: 50, xp: 700, abilities: ["Tail Spike Regrowth"], description: "A lion with bat wings and a tail covered in deadly spikes." },
    { id: 'wight', name: "Wight", type: "undead", challenge: 3, hp: 45, ac: 14, damage: "1d8+2", speed: 30, xp: 700, immunities: ["poison", "necrotic"], abilities: ["Life Drain", "Sunlight Sensitivity"], loot: ['sword_iron', 'armor_chain'], description: "An intelligent undead warrior animated by hatred of the living." },
    { id: 'basilisk', name: "Basilisk", type: "monstrosity", challenge: 3, hp: 52, ac: 15, damage: "2d6+3", speed: 20, xp: 700, abilities: ["Petrifying Gaze"], description: "An eight-legged reptile whose gaze turns creatures to stone." },

    // === CR 4-5 (Dangerous Enemies) ===
    { id: 'ettin', name: "Ettin", type: "giant", challenge: 4, hp: 85, ac: 12, damage: "2d8+5", speed: 40, xp: 1100, abilities: ["Two Heads", "Wakeful"], loot: ['axe_great', 'pot_heal'], description: "A two-headed giant, each head with its own vile personality." },
    { id: 'ghost', name: "Ghost", type: "undead", challenge: 4, hp: 45, ac: 11, damage: "4d6+3", speed: 40, xp: 1100, immunities: ["cold", "necrotic", "poison"], resistances: ["acid", "fire", "lightning", "thunder"], abilities: ["Etherealness", "Horrifying Visage", "Possession"], description: "The restless spirit of a tormented soul, seeking peace or vengeance." },
    { id: 'flameskull', name: "Flameskull", type: "undead", challenge: 4, hp: 40, ac: 13, damage: "3d6", speed: 40, xp: 1100, immunities: ["cold", "fire", "lightning", "necrotic", "poison"], abilities: ["Illumination", "Magic Resistance", "Rejuvenation"], description: "A floating skull wreathed in green flames, hurling fire at intruders." },
    { id: 'troll', name: "Troll", type: "giant", challenge: 5, hp: 84, ac: 15, damage: "2d6+4", speed: 30, xp: 1800, abilities: ["Keen Smell", "Regeneration"], vulnerabilities: ["fire", "acid"], description: "A lanky green-skinned brute that regenerates even the most grievous wounds." },
    { id: 'wraith', name: "Wraith", type: "undead", challenge: 5, hp: 67, ac: 13, damage: "4d8+3", speed: 60, xp: 1800, immunities: ["necrotic", "poison"], resistances: ["acid", "cold", "fire", "lightning", "thunder"], abilities: ["Life Drain", "Create Specter", "Incorporeal Movement"], description: "A powerful undead spirit cloaked in shadows and hatred." },
    { id: 'salamander', name: "Salamander", type: "elemental", challenge: 5, hp: 90, ac: 15, damage: "2d8+3", speed: 30, xp: 1800, immunities: ["fire"], vulnerabilities: ["cold"], abilities: ["Heated Body", "Heated Weapons"], description: "A serpentine elemental from the Plane of Fire." },
    { id: 'hill_giant', name: "Hill Giant", type: "giant", challenge: 5, hp: 105, ac: 13, damage: "3d8+5", speed: 40, xp: 1800, loot: ['axe_great', 'pot_heal', 'ration'], description: "A brutish giant with a voracious appetite for destruction." },
    { id: 'vampire_spawn', name: "Vampire Spawn", type: "undead", challenge: 5, hp: 82, ac: 15, damage: "2d6+3", speed: 30, xp: 1800, immunities: ["necrotic"], resistances: ["bludgeoning", "piercing", "slashing"], abilities: ["Regeneration", "Spider Climb", "Vampire Weaknesses"], description: "A newly-turned vampire, thrall to a more powerful master." },

    // === CR 6-8 (Very Dangerous Enemies) ===
    { id: 'medusa', name: "Medusa", type: "monstrosity", challenge: 6, hp: 127, ac: 15, damage: "2d6+2", speed: 30, xp: 2300, abilities: ["Petrifying Gaze"], loot: ['ring_prot', 'amulet_health'], description: "A cursed woman with snakes for hair and a petrifying gaze." },
    { id: 'cyclops', name: "Cyclops", type: "giant", challenge: 6, hp: 138, ac: 14, damage: "3d8+6", speed: 30, xp: 2300, abilities: ["Poor Depth Perception"], loot: ['axe_great'], description: "A one-eyed giant known for its brute strength and poor judgment." },
    { id: 'chimera', name: "Chimera", type: "monstrosity", challenge: 6, hp: 114, ac: 14, damage: "2d6+4", speed: 60, xp: 2300, abilities: ["Fire Breath"], description: "A three-headed beast with a lion, goat, and dragon head." },
    { id: 'young_dragon_black', name: "Young Black Dragon", type: "dragon", challenge: 7, hp: 127, ac: 18, damage: "2d10+4", speed: 80, xp: 2900, immunities: ["acid"], abilities: ["Acid Breath", "Amphibious"], loot: ['ring_prot', 'pot_heal'], description: "A vicious dragon that haunts swamps and delights in cruelty." },
    { id: 'young_dragon_green', name: "Young Green Dragon", type: "dragon", challenge: 8, hp: 136, ac: 18, damage: "2d10+4", speed: 80, xp: 3900, immunities: ["poison"], abilities: ["Poison Breath", "Amphibious"], loot: ['amulet_health'], description: "A cunning dragon that manipulates lesser creatures for its schemes." },
    { id: 'mind_flayer', name: "Mind Flayer", type: "aberration", challenge: 7, hp: 71, ac: 15, damage: "2d10+3", speed: 30, xp: 2900, abilities: ["Mind Blast", "Extract Brain", "Magic Resistance"], description: "An alien creature with a tentacled face that feeds on brains." },
    { id: 'frost_giant', name: "Frost Giant", type: "giant", challenge: 8, hp: 138, ac: 15, damage: "3d12+6", speed: 40, xp: 3900, immunities: ["cold"], loot: ['axe_great', 'pot_heal'], description: "A massive giant from frozen lands, wielding an enormous axe." },
    { id: 'stone_giant', name: "Stone Giant", type: "giant", challenge: 7, hp: 126, ac: 17, damage: "3d8+6", speed: 40, xp: 2900, abilities: ["Stone Camouflage"], description: "A reclusive giant that hurls boulders with deadly accuracy." },

    // === CR 9-12 (Deadly Enemies) ===
    { id: 'fire_giant', name: "Fire Giant", type: "giant", challenge: 9, hp: 162, ac: 18, damage: "3d12+7", speed: 30, xp: 5000, immunities: ["fire"], abilities: ["Heated Body"], loot: ['armor_plate', 'axe_great'], description: "A brutal giant smith wreathed in flames and hatred." },
    { id: 'bone_devil', name: "Bone Devil", type: "fiend", challenge: 9, hp: 142, ac: 19, damage: "3d8+5", speed: 40, xp: 5000, immunities: ["fire", "poison"], resistances: ["cold"], abilities: ["Devil's Sight", "Magic Resistance"], description: "A skeletal fiend that serves as a lieutenant of Hell." },
    { id: 'cloud_giant', name: "Cloud Giant", type: "giant", challenge: 9, hp: 200, ac: 14, damage: "3d8+8", speed: 40, xp: 5000, abilities: ["Keen Smell", "Innate Spellcasting"], loot: ['armor_plate', 'ring_prot'], description: "A giant dwelling among the clouds, wielding powerful magic." },
    { id: 'adult_dragon_white', name: "Adult White Dragon", type: "dragon", challenge: 10, hp: 200, ac: 18, damage: "2d10+6", speed: 80, xp: 5900, immunities: ["cold"], abilities: ["Cold Breath", "Ice Walk"], loot: ['armor_plate', 'ring_prot', 'amulet_health'], description: "A savage dragon of the frozen north, driven by animal cunning." },
    { id: 'beholder', name: "Beholder", type: "aberration", challenge: 13, hp: 180, ac: 18, damage: "4d8+4", speed: 20, xp: 10000, abilities: ["Antimagic Cone", "Eye Rays"], loot: ['ring_prot', 'amulet_health', 'pot_heal'], description: "A floating orb of hatred with a central eye and many eyestalks." },
    { id: 'adult_dragon_red', name: "Adult Red Dragon", type: "dragon", challenge: 17, hp: 256, ac: 19, damage: "2d10+8", speed: 80, xp: 18000, immunities: ["fire"], abilities: ["Fire Breath", "Legendary Resistance", "Frightful Presence"], loot: ['armor_plate', 'ring_prot', 'amulet_health'], description: "The most fearsome of dragons, a tyrant of flame and destruction." },
    { id: 'lich', name: "Lich", type: "undead", challenge: 21, hp: 135, ac: 17, damage: "3d6", speed: 30, xp: 33000, immunities: ["poison", "necrotic"], abilities: ["Legendary Resistance", "Rejuvenation", "Spellcasting", "Paralyzing Touch"], loot: ['ring_prot', 'amulet_health', 'book_spell'], description: "An undead archmage who achieved immortality through dark rituals." },
    { id: 'ancient_dragon_gold', name: "Ancient Gold Dragon", type: "dragon", challenge: 24, hp: 546, ac: 22, damage: "2d10+10", speed: 80, xp: 62000, immunities: ["fire"], abilities: ["Fire Breath", "Weakening Breath", "Legendary Resistance", "Frightful Presence", "Change Shape"], description: "A benevolent but terrifyingly powerful ancient wyrm." },
    { id: 'tarrasque', name: "Tarrasque", type: "monstrosity", challenge: 30, hp: 676, ac: 25, damage: "4d12+10", speed: 40, xp: 155000, immunities: ["fire", "poison"], abilities: ["Legendary Resistance", "Magic Resistance", "Reflective Carapace", "Siege Monster"], description: "The most dreaded creature in existence, a world-ending titan." },
];

// === WORLD LOCATIONS ===
export const LOCATIONS_DB: LocationData[] = [
    // === Starting Areas ===
    { id: 'willowmere', name: "Willowmere Village", type: "town", description: "A peaceful farming village nestled in rolling hills, known for its warm hospitality and excellent ale.", connections: ['crossroads', 'whispering_woods', 'millbrook_farm'], npcs: ['elder_mira', 'blacksmith_thorn'], shops: ['general_store', 'tavern'], dangerLevel: 0 },
    { id: 'crossroads', name: "The Crossroads", type: "landmark", description: "A well-traveled intersection where four roads meet, marked by an ancient stone milestone.", connections: ['willowmere', 'ravenshollow', 'duskfall_ruins', 'merchant_pass'], monsters: ['goblin', 'kobold', 'wolf'], dangerLevel: 1 },
    { id: 'millbrook_farm', name: "Millbrook Farm", type: "landmark", description: "A prosperous farmstead with golden wheat fields and a creaking windmill.", connections: ['willowmere', 'whispering_woods'], monsters: ['rat', 'wolf'], dangerLevel: 1 },

    // === Wilderness ===
    { id: 'whispering_woods', name: "Whispering Woods", type: "wilderness", description: "An ancient forest where the trees seem to whisper secrets. Sunlight barely penetrates the dense canopy.", connections: ['willowmere', 'millbrook_farm', 'druid_grove', 'spider_hollow'], monsters: ['wolf', 'dire_wolf', 'giant_spider', 'owlbear'], dangerLevel: 3 },
    { id: 'spider_hollow', name: "Spider Hollow", type: "dungeon", description: "A web-choked ravine infested with giant spiders of all sizes.", connections: ['whispering_woods'], monsters: ['giant_spider'], dangerLevel: 4 },
    { id: 'druid_grove', name: "Druid's Grove", type: "temple", description: "A sacred clearing where druids commune with nature spirits around a moonlit pool.", connections: ['whispering_woods'], npcs: ['archdruid_oak'], dangerLevel: 1 },
    { id: 'merchant_pass', name: "Merchant's Pass", type: "wilderness", description: "A mountain road frequented by traders, though bandits lurk in the rocky outcrops.", connections: ['crossroads', 'ironhold', 'bandit_camp'], monsters: ['goblin', 'hobgoblin', 'bugbear'], dangerLevel: 3 },
    { id: 'bandit_camp', name: "Bandit Camp", type: "dungeon", description: "A hidden encampment where outlaws count their ill-gotten gains.", connections: ['merchant_pass'], monsters: ['hobgoblin', 'bugbear'], dangerLevel: 4 },

    // === Towns & Cities ===
    { id: 'ravenshollow', name: "Ravenshollow", type: "town", description: "A fog-shrouded town on the edge of cursed marshlands, its inhabitants wary of strangers.", connections: ['crossroads', 'marshes_of_sorrow', 'raven_manor'], npcs: ['mayor_corvus', 'witch_elara'], shops: ['apothecary', 'curiosities'], dangerLevel: 2 },
    { id: 'ironhold', name: "Ironhold Citadel", type: "castle", description: "A dwarven fortress carved into the mountainside, its forges burning day and night.", connections: ['merchant_pass', 'deep_mines', 'frozen_peaks'], npcs: ['king_thorin', 'master_smith'], shops: ['dwarven_armory', 'gem_merchant'], dangerLevel: 1 },
    { id: 'silverspire', name: "Silverspire City", type: "town", description: "The gleaming capital city, its towers reaching toward the heavens, center of magic and commerce.", connections: ['kings_road', 'mage_academy', 'noble_quarter'], npcs: ['archmage_vexis', 'queen_alara'], shops: ['grand_bazaar', 'enchanter', 'royal_armory'], dangerLevel: 0 },

    // === Dungeons & Ruins ===
    { id: 'duskfall_ruins', name: "Duskfall Ruins", type: "ruin", description: "Crumbling remains of an ancient elven city, now home to the restless dead.", connections: ['crossroads', 'catacombs'], monsters: ['skeleton', 'zombie', 'ghost', 'wight'], dangerLevel: 4 },
    { id: 'catacombs', name: "The Catacombs", type: "dungeon", description: "Endless tunnels beneath Duskfall where the dead refuse to stay buried.", connections: ['duskfall_ruins', 'lich_sanctum'], monsters: ['skeleton', 'zombie', 'ghoul', 'ghast', 'wraith'], dangerLevel: 6 },
    { id: 'lich_sanctum', name: "Lich's Sanctum", type: "dungeon", description: "The hidden phylactery chamber of an ancient lich, pulsing with dark energy.", connections: ['catacombs'], monsters: ['lich', 'wraith', 'flameskull'], dangerLevel: 10 },
    { id: 'raven_manor', name: "Raven Manor", type: "dungeon", description: "A decrepit mansion where a vampire lord holds court over the damned.", connections: ['ravenshollow'], monsters: ['vampire_spawn', 'ghost', 'specter'], dangerLevel: 6 },
    { id: 'marshes_of_sorrow', name: "Marshes of Sorrow", type: "wilderness", description: "A fetid swamp where will-o-wisps lead travelers to watery graves.", connections: ['ravenshollow', 'hag_lair', 'lizardfolk_village'], monsters: ['zombie', 'ghoul', 'shadow'], dangerLevel: 5 },
    { id: 'hag_lair', name: "Hag's Lair", type: "dungeon", description: "A twisted hovel where a coven of hags brew terrible curses.", connections: ['marshes_of_sorrow'], monsters: ['harpy', 'ghast'], dangerLevel: 5 },

    // === Mountain & Underground ===
    { id: 'deep_mines', name: "Deep Mines", type: "dungeon", description: "Abandoned dwarven mines that delved too deep, awakening ancient horrors.", connections: ['ironhold', 'underdark_gate'], monsters: ['kobold', 'gargoyle', 'basilisk'], dangerLevel: 5 },
    { id: 'underdark_gate', name: "Underdark Gate", type: "dungeon", description: "A yawning portal to the lightless depths below, guarded by aberrations.", connections: ['deep_mines'], monsters: ['mind_flayer', 'beholder'], dangerLevel: 9 },
    { id: 'frozen_peaks', name: "Frozen Peaks", type: "wilderness", description: "Treacherous mountain summits where frost giants make their homes.", connections: ['ironhold', 'frost_giant_hold', 'dragon_eyrie'], monsters: ['wolf', 'dire_wolf', 'frost_giant'], dangerLevel: 7 },
    { id: 'frost_giant_hold', name: "Frost Giant Hold", type: "castle", description: "An ice fortress carved from a glacier, home to a frost giant jarl.", connections: ['frozen_peaks'], monsters: ['frost_giant', 'werewolf'], dangerLevel: 8 },
    { id: 'dragon_eyrie', name: "Dragon's Eyrie", type: "dungeon", description: "A mountain peak lair where an ancient dragon broods over its hoard.", connections: ['frozen_peaks'], monsters: ['adult_dragon_red', 'young_dragon_black'], dangerLevel: 10 },

    // === Special Locations ===
    { id: 'mage_academy', name: "Arcane Academy", type: "guild", description: "A floating tower where aspiring wizards learn the secrets of magic.", connections: ['silverspire'], npcs: ['archmage_vexis', 'librarian_scrolls'], shops: ['spell_components', 'scroll_shop'], dangerLevel: 0 },
    { id: 'temple_of_light', name: "Temple of the Dawn", type: "temple", description: "A grand cathedral dedicated to the sun god, its spires catching the first light of day.", connections: ['silverspire', 'celestial_sanctum'], npcs: ['high_priest_solara'], dangerLevel: 0 },
    { id: 'celestial_sanctum', name: "Celestial Sanctum", type: "temple", description: "A hidden holy site where clerics commune with celestial beings.", connections: ['temple_of_light'], dangerLevel: 2 },
    { id: 'thieves_guild', name: "Shadow Market", type: "guild", description: "A secret underground bazaar where anything can be bought for the right price.", connections: ['silverspire'], npcs: ['guildmaster_shade'], shops: ['black_market', 'poison_vendor'], dangerLevel: 3 },
    { id: 'arena', name: "The Colosseum", type: "landmark", description: "A grand arena where warriors test their mettle against beasts and each other.", connections: ['silverspire'], npcs: ['arena_master'], monsters: ['ogre', 'troll', 'manticore'], dangerLevel: 4 },
    { id: 'plane_of_fire', name: "Plane of Fire", type: "dungeon", description: "A portal to the elemental plane of fire, where salamanders and efreet dwell.", connections: ['mage_academy'], monsters: ['salamander', 'fire_giant'], dangerLevel: 8 },
    { id: 'abyss_gate', name: "Abyssal Rift", type: "dungeon", description: "A tear in reality leading to the demonic Abyss, sealed by ancient wards.", connections: ['catacombs'], monsters: ['bone_devil', 'wraith'], dangerLevel: 10 },
];

// === ACHIEVEMENTS ===
export const ACHIEVEMENTS_DB: Achievement[] = [
    // === Combat Achievements ===
    { id: 'first_blood', name: "First Blood", description: "Defeat your first enemy in combat.", icon: "sword", category: "combat", requirement: { type: "kills", count: 1 }, reward: { xp: 50 } },
    { id: 'goblin_slayer', name: "Goblin Slayer", description: "Defeat 10 goblins.", icon: "skull", category: "combat", requirement: { type: "kills", target: "goblin", count: 10 }, reward: { xp: 200, title: "Goblin Slayer" } },
    { id: 'undead_hunter', name: "Undead Hunter", description: "Defeat 25 undead creatures.", icon: "ghost", category: "combat", requirement: { type: "kills", target: "undead", count: 25 }, reward: { xp: 500, title: "Undead Hunter" } },
    { id: 'dragon_slayer', name: "Dragon Slayer", description: "Defeat any dragon.", icon: "dragon", category: "combat", requirement: { type: "kills", target: "dragon", count: 1 }, reward: { xp: 2000, title: "Dragon Slayer", item: "ring_prot" } },
    { id: 'giant_killer', name: "Giant Killer", description: "Defeat 5 giants of any type.", icon: "mountain", category: "combat", requirement: { type: "kills", target: "giant", count: 5 }, reward: { xp: 1000, title: "Giant Killer" } },
    { id: 'monster_hunter', name: "Monster Hunter", description: "Defeat 100 enemies.", icon: "target", category: "combat", requirement: { type: "kills", count: 100 }, reward: { xp: 1500, title: "Monster Hunter" } },
    { id: 'legendary_warrior', name: "Legendary Warrior", description: "Defeat 500 enemies.", icon: "crown", category: "combat", requirement: { type: "kills", count: 500 }, reward: { xp: 5000, title: "Legendary Warrior" } },
    { id: 'lich_bane', name: "Lich Bane", description: "Defeat a lich.", icon: "skull", category: "combat", requirement: { type: "kills", target: "lich", count: 1 }, reward: { xp: 5000, title: "Lich Bane" } },
    { id: 'beholder_slayer', name: "Beholder Slayer", description: "Defeat a beholder.", icon: "eye", category: "combat", requirement: { type: "kills", target: "beholder", count: 1 }, reward: { xp: 3000, title: "Eye Closer" } },

    // === Exploration Achievements ===
    { id: 'first_steps', name: "First Steps", description: "Visit your first location outside the starting village.", icon: "map", category: "exploration", requirement: { type: "visits", count: 2 }, reward: { xp: 25 } },
    { id: 'wanderer', name: "Wanderer", description: "Visit 10 different locations.", icon: "compass", category: "exploration", requirement: { type: "visits", count: 10 }, reward: { xp: 300, title: "Wanderer" } },
    { id: 'explorer', name: "Explorer", description: "Visit 25 different locations.", icon: "map-pin", category: "exploration", requirement: { type: "visits", count: 25 }, reward: { xp: 1000, title: "Explorer" } },
    { id: 'world_traveler', name: "World Traveler", description: "Visit every location in the world.", icon: "globe", category: "exploration", requirement: { type: "visits", count: 30 }, reward: { xp: 3000, title: "World Traveler" } },
    { id: 'dungeon_delver', name: "Dungeon Delver", description: "Explore 5 dungeons.", icon: "dungeon", category: "exploration", requirement: { type: "visits", target: "dungeon", count: 5 }, reward: { xp: 500, title: "Dungeon Delver" } },
    { id: 'underdark_explorer', name: "Underdark Explorer", description: "Venture into the Underdark.", icon: "cave", category: "exploration", requirement: { type: "visits", target: "underdark_gate", count: 1 }, reward: { xp: 1000 } },
    { id: 'dragon_lair', name: "Into the Dragon's Den", description: "Enter a dragon's lair.", icon: "fire", category: "exploration", requirement: { type: "visits", target: "dragon_eyrie", count: 1 }, reward: { xp: 500 } },

    // === Collection Achievements ===
    { id: 'collector', name: "Collector", description: "Collect 25 different items.", icon: "package", category: "collection", requirement: { type: "items", count: 25 }, reward: { xp: 300 } },
    { id: 'hoarder', name: "Hoarder", description: "Collect 100 items total.", icon: "chest", category: "collection", requirement: { type: "items", count: 100 }, reward: { xp: 1000, title: "Hoarder" } },
    { id: 'wealthy', name: "Wealthy", description: "Accumulate 10,000 gold.", icon: "coins", category: "collection", requirement: { type: "gold", count: 10000 }, reward: { xp: 500 } },
    { id: 'rich', name: "Rich", description: "Accumulate 50,000 gold.", icon: "gem", category: "collection", requirement: { type: "gold", count: 50000 }, reward: { xp: 1500, title: "Wealthy Adventurer" } },
    { id: 'filthy_rich', name: "Filthy Rich", description: "Accumulate 250,000 gold.", icon: "crown", category: "collection", requirement: { type: "gold", count: 250000 }, reward: { xp: 5000, title: "Tycoon" } },
    { id: 'spell_collector', name: "Spell Collector", description: "Learn 10 different spells.", icon: "book", category: "collection", requirement: { type: "spells", count: 10 }, reward: { xp: 500 } },
    { id: 'arcane_master', name: "Arcane Master", description: "Learn 25 different spells.", icon: "sparkles", category: "collection", requirement: { type: "spells", count: 25 }, reward: { xp: 1500, title: "Arcane Master" } },

    // === Progression Achievements ===
    { id: 'level_5', name: "Adventurer", description: "Reach level 5.", icon: "trending-up", category: "progression", requirement: { type: "level", count: 5 }, reward: { xp: 200 } },
    { id: 'level_10', name: "Veteran", description: "Reach level 10.", icon: "award", category: "progression", requirement: { type: "level", count: 10 }, reward: { xp: 500, title: "Veteran" } },
    { id: 'level_15', name: "Champion", description: "Reach level 15.", icon: "star", category: "progression", requirement: { type: "level", count: 15 }, reward: { xp: 1000, title: "Champion" } },
    { id: 'level_20', name: "Legend", description: "Reach level 20.", icon: "crown", category: "progression", requirement: { type: "level", count: 20 }, reward: { xp: 3000, title: "Living Legend" } },
    { id: 'quest_complete', name: "Quest Complete", description: "Complete your first quest.", icon: "check", category: "progression", requirement: { type: "quests", count: 1 }, reward: { xp: 100 } },
    { id: 'quest_master', name: "Quest Master", description: "Complete 25 quests.", icon: "clipboard-check", category: "progression", requirement: { type: "quests", count: 25 }, reward: { xp: 2000, title: "Quest Master" } },

    // === Social Achievements ===
    { id: 'friendly', name: "Friendly", description: "Meet 5 different NPCs.", icon: "users", category: "social", requirement: { type: "custom", count: 5 }, reward: { xp: 100 } },
    { id: 'diplomat', name: "Diplomat", description: "Resolve a conflict peacefully.", icon: "handshake", category: "social", requirement: { type: "custom", count: 1 }, reward: { xp: 300, title: "Diplomat" } },
    { id: 'guild_member', name: "Guild Member", description: "Join a guild.", icon: "shield", category: "social", requirement: { type: "custom", count: 1 }, reward: { xp: 200 } },

    // === Secret Achievements ===
    { id: 'tarrasque_survivor', name: "Tarrasque Survivor", description: "Survive an encounter with a tarrasque.", icon: "skull", category: "secret", requirement: { type: "custom", count: 1 }, reward: { xp: 10000, title: "World's Luckiest" } },
    { id: 'mind_flayer_escape', name: "Mind Intact", description: "Escape from a mind flayer without losing your mind.", icon: "brain", category: "secret", requirement: { type: "kills", target: "mind_flayer", count: 1 }, reward: { xp: 2000 } },
    { id: 'pacifist', name: "Pacifist", description: "Complete a dungeon without killing anyone.", icon: "dove", category: "secret", requirement: { type: "custom", count: 1 }, reward: { xp: 1000, title: "Pacifist" } },
    { id: 'from_ashes', name: "From the Ashes", description: "Be revived from death.", icon: "heart", category: "secret", requirement: { type: "custom", count: 1 }, reward: { xp: 500 } },
    { id: 'against_odds', name: "Against All Odds", description: "Win a battle with less than 5 HP remaining.", icon: "zap", category: "secret", requirement: { type: "custom", count: 1 }, reward: { xp: 500, title: "Lucky" } },
];